### PR TITLE
Add in Dockerfiles for ubuntu 16.04 images

### PR DESCRIPTION
**Pull request by alexwishart**
## Description
Adding in Dockerfiles for the following images:
- ibmcom/ubuntu:16.04
- ibmcom/swift-ubuntu-xenial-amd64
- ibmcom/swift-ubuntu-xenial-s390x
and a manifest for the multi-arch image ibmcom/swift-ubuntu-xenial

Have updated README and added amd64 images into the travis script so they can be automatically built and pushed.

## Motivation and Context
To get a sample app into IBM Cloud Private, we need a docker image that can run on Ubuntu 16.04. This is part of the work facilitating that, as well as allowing a sample app to be run on zLinux.

## How Has This Been Tested?
Docker images have been tested with a sample app on both architectures 

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by rolivieri** [comment]
Hello @alexwishart, answering your slack message over here. We should also get a formal review from the current repo owners (@sandmman and/or @christiancompton, assuming they are still part of the Swift effort). A few points:

1) We have development and runtime docker images for ubuntu 14.04 (see the swift-development and swift-runtime folders). I recommend following this same pattern/approach for anything new. For instance, if we are to add support for ubuntu 16.04, we should have a development image and a runtime image as for 16.04. 

2) To implement #1 above, I'd recommend keeping the high level folders (e.g. swift-development and swift-runtime) as they are and introduce sub-folders for 14.04, 16.04, etc). 

3) If in addition to ubuntu 16.04, there is also a need to support s390x, I would also recommend the same approach for that platform: development and runtime images.

**Comment by alexwishart** [comment]
@rolivieri could you have a look at my changes? 🙂 The travis build is still failing because of incorrect credentials, but I think there's some confusion as the PR is from the master branch of my fork, so the docker pushes which are protected by checking if the travis branch is master are occurring when they shouldn't be. Not sure how travis is set up, but do you think the build will pass if the PR is based on a differently named branch?

**Comment by sandmman** [comment]
@alexwishart I'll take a look. Travis does not provide these values to untrusted builds (i.e triggered by pull requests from another repository). I've moved your work to an internal branch and its being tested in another PR #48.

**Comment by sandmman** [comment]
This is being closed. It has been moved to #48

**Pull request closed without merging**
