### PR TITLE
Updated to Swift v4.0.2

### PR DESCRIPTION
**Pull request by graemer957**

### CODE REVIEW

**Comment by rolivieri** [comment]
@graemer957 Thanks for the PR! Before we can process the PR, can you over the checklist below? We now have a PR template (when you opened the PR we did not have one in place). If you have contributed before our GitHub org, then you should have a CLA in place. Look forward to hearing from you.

## Checklist:


- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

**Comment by graemer957** [comment]
Hello @rolivieri, I have just submitted our CLA form. Here is my checklist:

- [x] I have submitted a CLA form
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

**Comment by rolivieri** [comment]
@graemer957 Great, thanks so much! We will merge into develop and after CI build completes we will merge into master.

**Comment by graemer957** [comment]
@rolivieri No problem, thank you.

**Pull request merged**
